services:
  - type: web
    name: madhushala-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn server.main:app --host 0.0.0.0 --port 8000"
    autoDeploy: true

  - type: web
    name: madhushala-ui
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run ui/app.py --server.port 8001"
    autoDeploy: true
